#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : gperftools
Version  : 2.15
Release  : 27
URL      : https://github.com/gperftools/gperftools/releases/download/gperftools-2.15/gperftools-2.15.tar.gz
Source0  : https://github.com/gperftools/gperftools/releases/download/gperftools-2.15/gperftools-2.15.tar.gz
Summary  : @CMAKE_PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : BSD-3-Clause
Requires: gperftools-bin = %{version}-%{release}
Requires: gperftools-lib = %{version}-%{release}
Requires: gperftools-license = %{version}-%{release}
Requires: gperftools-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : libunwind-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
gperftools
----------
(originally Google Performance Tools)
The fastest malloc we’ve seen; works particularly well with threads
and STL. Also: thread-friendly heap-checker, heap-profiler, and
cpu-profiler.

%package bin
Summary: bin components for the gperftools package.
Group: Binaries
Requires: gperftools-license = %{version}-%{release}

%description bin
bin components for the gperftools package.


%package dev
Summary: dev components for the gperftools package.
Group: Development
Requires: gperftools-lib = %{version}-%{release}
Requires: gperftools-bin = %{version}-%{release}
Provides: gperftools-devel = %{version}-%{release}
Requires: gperftools = %{version}-%{release}

%description dev
dev components for the gperftools package.


%package doc
Summary: doc components for the gperftools package.
Group: Documentation
Requires: gperftools-man = %{version}-%{release}

%description doc
doc components for the gperftools package.


%package lib
Summary: lib components for the gperftools package.
Group: Libraries
Requires: gperftools-license = %{version}-%{release}

%description lib
lib components for the gperftools package.


%package license
Summary: license components for the gperftools package.
Group: Default

%description license
license components for the gperftools package.


%package man
Summary: man components for the gperftools package.
Group: Default

%description man
man components for the gperftools package.


%prep
%setup -q -n gperftools-2.15
cd %{_builddir}/gperftools-2.15
pushd ..
cp -a gperftools-2.15 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720032910
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720032910
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gperftools
cp %{_builddir}/gperftools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gperftools/40cce6f974f678788e7de2fb9928258219416c82 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pprof
/usr/bin/pprof-symbolize

%files dev
%defattr(-,root,root,-)
/usr/include/google/heap-checker.h
/usr/include/google/heap-profiler.h
/usr/include/google/malloc_extension.h
/usr/include/google/malloc_extension_c.h
/usr/include/google/malloc_hook.h
/usr/include/google/malloc_hook_c.h
/usr/include/google/profiler.h
/usr/include/google/stacktrace.h
/usr/include/google/tcmalloc.h
/usr/include/gperftools/heap-checker.h
/usr/include/gperftools/heap-profiler.h
/usr/include/gperftools/malloc_extension.h
/usr/include/gperftools/malloc_extension_c.h
/usr/include/gperftools/malloc_hook.h
/usr/include/gperftools/malloc_hook_c.h
/usr/include/gperftools/nallocx.h
/usr/include/gperftools/profiler.h
/usr/include/gperftools/stacktrace.h
/usr/include/gperftools/tcmalloc.h
/usr/lib64/libprofiler.so
/usr/lib64/libtcmalloc.so
/usr/lib64/libtcmalloc_and_profiler.so
/usr/lib64/libtcmalloc_debug.so
/usr/lib64/libtcmalloc_minimal.so
/usr/lib64/libtcmalloc_minimal_debug.so
/usr/lib64/pkgconfig/libprofiler.pc
/usr/lib64/pkgconfig/libtcmalloc.pc
/usr/lib64/pkgconfig/libtcmalloc_debug.pc
/usr/lib64/pkgconfig/libtcmalloc_minimal.pc
/usr/lib64/pkgconfig/libtcmalloc_minimal_debug.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/gperftools/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libprofiler.so.0.5.11
/V3/usr/lib64/libtcmalloc.so.4.5.16
/V3/usr/lib64/libtcmalloc_and_profiler.so.4.6.11
/V3/usr/lib64/libtcmalloc_debug.so.4.5.16
/V3/usr/lib64/libtcmalloc_minimal.so.4.5.16
/V3/usr/lib64/libtcmalloc_minimal_debug.so.4.5.16
/usr/lib64/libprofiler.so.0
/usr/lib64/libprofiler.so.0.5.11
/usr/lib64/libtcmalloc.so.4
/usr/lib64/libtcmalloc.so.4.5.16
/usr/lib64/libtcmalloc_and_profiler.so.4
/usr/lib64/libtcmalloc_and_profiler.so.4.6.11
/usr/lib64/libtcmalloc_debug.so.4
/usr/lib64/libtcmalloc_debug.so.4.5.16
/usr/lib64/libtcmalloc_minimal.so.4
/usr/lib64/libtcmalloc_minimal.so.4.5.16
/usr/lib64/libtcmalloc_minimal_debug.so.4
/usr/lib64/libtcmalloc_minimal_debug.so.4.5.16

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gperftools/40cce6f974f678788e7de2fb9928258219416c82

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pprof.1
